package swc.robotics.scouting.system;

import javax.swing.JOptionPane;

/**
 * Project Name: SWC Robotics Scouting System
 * File Name:	 MainMenu
 * Programmer:	 Phil Bystrican <Phil@PBApps.ca>
 * Teacher:	 Mr. K
 * Date:         Mar 3, 2014
 * Description:  JFrame with contains the main menu for the application.
 **/

public class MainMenu extends BaseJFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();

        //center the jframe
        this.setLocationRelativeTo(null);
        //this frame has no parent
        this.parent = null;

        
        //set the path to the sqlite 4 java libs
       // System.setProperty("sqlite4java.library.path", "sqlite4java-282/");

        //set the log level to warning and higher
        java.util.logging.Logger.getLogger("com.almworks.sqlite4java").setLevel(java.util.logging.Level.WARNING);

        //create the database and the tables
        DataBaseManager.createDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_newTeam = new javax.swing.JButton();
        btn_modifyTeam = new javax.swing.JButton();
        btn_modifyGame = new javax.swing.JButton();
        btn_newGame = new javax.swing.JButton();
        btn_sortData = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FRC Scouting System");

        btn_newTeam.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btn_newTeam.setForeground(new java.awt.Color(0, 153, 0));
        btn_newTeam.setText("New Team");
        btn_newTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newTeamActionPerformed(evt);
            }
        });

        btn_modifyTeam.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btn_modifyTeam.setForeground(new java.awt.Color(0, 153, 0));
        btn_modifyTeam.setText("Modify Existing Team");
        btn_modifyTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifyTeamActionPerformed(evt);
            }
        });

        btn_modifyGame.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btn_modifyGame.setForeground(new java.awt.Color(0, 0, 153));
        btn_modifyGame.setText("Modify Existing Game");
        btn_modifyGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifyGameActionPerformed(evt);
            }
        });

        btn_newGame.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btn_newGame.setForeground(new java.awt.Color(0, 0, 153));
        btn_newGame.setText("New Game");
        btn_newGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newGameActionPerformed(evt);
            }
        });

        btn_sortData.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btn_sortData.setForeground(new java.awt.Color(102, 0, 0));
        btn_sortData.setText("Sort And Compare Data");
        btn_sortData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sortDataActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                    .add(btn_newTeam, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, btn_modifyTeam, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(btn_newGame, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, btn_modifyGame, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(btn_sortData, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btn_newTeam, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btn_modifyTeam, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btn_newGame, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btn_modifyGame, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btn_sortData, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*takes the event as a parameter. Opens the new team jframe. returns nothing*/
    private void btn_newTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newTeamActionPerformed
        //initialize the new team jframe
        NewTeam jfrm_newTeam = new NewTeam();
        //display the jframe
        super.pushFrame(jfrm_newTeam, this);
    }//GEN-LAST:event_btn_newTeamActionPerformed

    /*takes the event as a parameter. Requests a team number, validates the 
     * input and opens the modify team jframe. returns nothing*/
    private void btn_modifyTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifyTeamActionPerformed
        //show the user a dialog box to get their imput
        String str_inputValue = 
                JOptionPane.showInputDialog("Input the team number to modify:");

        //if nothing was inputed
        if (str_inputValue == null) {
            //cancel was pressed
            return;
        }
        try {
            //if the parsed integer is 0
            if (Integer.parseInt(str_inputValue) == 0) {
                //get the input again
                btn_modifyTeamActionPerformed(null);
            } else {
                //initialize the modify team jframe
                ModifyTeam jfrm_modifyTeam = 
                        new ModifyTeam(Integer.parseInt(str_inputValue), false);
                //display the jframe
                super.pushFrame(jfrm_modifyTeam, this);
                //call the frame's became visible method which checks if the entered team exists
                jfrm_modifyTeam.becameVisible();
            }
        } catch (NumberFormatException ex) {
            //an improper integer such as a letter was entered
            //get the input again
            btn_modifyTeamActionPerformed(null);
        }
    }//GEN-LAST:event_btn_modifyTeamActionPerformed

    /*takes the event as a parameter. Opens the new game jframe. returns nothing*/
    private void btn_newGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newGameActionPerformed
        //initialize the new game jframe
        NewMatch jfrm_newMatch = new NewMatch();
        //display the jframe
        super.pushFrame(jfrm_newMatch, this);
    }//GEN-LAST:event_btn_newGameActionPerformed

    /*takes the event as a parameter. Requests a match number, validates the input and opens the modify match jframe. returns nothing*/
    private void btn_modifyGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifyGameActionPerformed
        //show the user a dialog box to get their imput
        String str_inputValue = JOptionPane.showInputDialog("Input the match number to modify:");

        //if nothing was inputed
        if (str_inputValue == null) {
            //do nothing
            return;
        }
        try {
            //if the parsed integer is 0
            if (Integer.parseInt(str_inputValue) == 0) {
                //get the input again
                btn_modifyGameActionPerformed(null);
            } else {
                //initialize the modify team jframe
                ModifyMatchScoring jfrm_modifyMatch = new ModifyMatchScoring(Integer.parseInt(str_inputValue));
                //display the jframe
                super.pushFrame(jfrm_modifyMatch, this);
                //call the frame's became visible method which checks if the entered team exists
                jfrm_modifyMatch.becameVisible();
            }
        } catch (NumberFormatException ex) {
            //an improper integer such as a letter was entered
            //get the input again
            btn_modifyGameActionPerformed(null);
        }
    }//GEN-LAST:event_btn_modifyGameActionPerformed

    /*takes the event as a parameter. Opens the t data jframe. returns nothing*/
    private void btn_sortDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sortDataActionPerformed
        //initialize the data sorting jframe
        SortData jfrm_sortData = new SortData();
        //display the jframe
        super.pushFrame(jfrm_sortData, this);
    }//GEN-LAST:event_btn_sortDataActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_modifyGame;
    private javax.swing.JButton btn_modifyTeam;
    private javax.swing.JButton btn_newGame;
    private javax.swing.JButton btn_newTeam;
    private javax.swing.JButton btn_sortData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
