package swc.robotics.scouting.system;

import javax.swing.JOptionPane;
import java.util.Observable;

/**
 * Project Name: SWC Robotics Scouting System
 * File Name:	 ModifyTeam
 * Programmer:	 Phil Bystrican <Phil@PBApps.ca>
 * Teacher:	 Mr. K
 * Date:         Mar 6, 2014
 * Description:  JFrame used to modify the information of a single team.
 **/
public class ModifyTeam extends BaseJFrame {

    //variable for the team that is to be modified
    FRCTeam frct_team; 
    
    /** Creates new form ModifyTeam  with the team number as a parameter*/
    public ModifyTeam(int int_teamNumber, boolean bool_ignoreMissingTeam) {
        //init frame components
        initComponents();
        
        //load the team from the database
        frct_team = DataBaseManager.loadTeam(int_teamNumber);   
        
        //check if a mising team (from the db) should be ignored
        if (bool_ignoreMissingTeam)
        {
            //set the team number to the entered team number
            frct_team.int_teamNumber = int_teamNumber;
        }
        
        //set the team number text to that from the database (it is not editable)
        lbl_teamNumber.setText("Team Number: " + frct_team.int_teamNumber);
        
        
        //check if the robot-type int represents a goalie type
        if (frct_team.int_robotType - Constants.int_GOALIE >= 0)
        {
            //check the goalie box to checked
            chkbx_goalieType.setSelected(true);
            //subtract the goalie value from the robot type to determine if the robot is of another type
            frct_team.int_robotType -= Constants.int_GOALIE;
        }
        //check if the robot-type int represents a passing type
        if (frct_team.int_robotType - Constants.int_PASSING >= 0)
        {
            //check the passing box to checked
            chkbx_passingType.setSelected(true);
            //subtract the passing value from the robot type to determine if the robot is a scoring type
            frct_team.int_robotType -= Constants.int_PASSING;
        }
        //check if the robot-type int represents a scoring type
        if (frct_team.int_robotType - Constants.int_SCORING >= 0)
        {
            //check the scoring box to checked
            chkbx_scoringType.setSelected(true);
            //subtract the passing value from the robot type
            frct_team.int_robotType -= Constants.int_SCORING;
        }
        //set the team name text to that from the database
        txtfld_teamName.setText(frct_team.str_teamName);
        //set the team strengths text to that from the database
        txtfld_strengths.setText(frct_team.str_strengths);
        //set the team weaknesses text to that from the database
        txtfld_weaknesses.setText(frct_team.str_weaknesses);
        //set the notes text to that from the database
        txtpn_notes.setText(frct_team.str_notes);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        btn_delete = new javax.swing.JButton();
        lbl_teamNumber = new javax.swing.JLabel();
        txtfld_teamName = new javax.swing.JTextField();
        lbl_teamName = new javax.swing.JLabel();
        lbl_robotType = new javax.swing.JLabel();
        chkbx_passingType = new javax.swing.JCheckBox();
        chkbx_scoringType = new javax.swing.JCheckBox();
        chkbx_goalieType = new javax.swing.JCheckBox();
        txtfld_strengths = new javax.swing.JTextField();
        lbl_robotStrengths = new javax.swing.JLabel();
        txtfld_weaknesses = new javax.swing.JTextField();
        lbl_robotWeaknesses = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtpn_notes = new javax.swing.JTextPane();
        lbl_notes = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        lbl_title.setBackground(new java.awt.Color(255, 255, 255));
        lbl_title.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_title.setText("Modify Team");

        btn_delete.setForeground(new java.awt.Color(204, 0, 0));
        btn_delete.setText("Delete Team");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        lbl_teamNumber.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lbl_teamNumber.setForeground(new java.awt.Color(255, 255, 255));
        lbl_teamNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_teamNumber.setText("Team Number: 0");

        txtfld_teamName.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lbl_teamName.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lbl_teamName.setForeground(new java.awt.Color(255, 255, 255));
        lbl_teamName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_teamName.setText("Team Name");

        lbl_robotType.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lbl_robotType.setForeground(new java.awt.Color(255, 255, 255));
        lbl_robotType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_robotType.setText("Type of Robot");

        chkbx_passingType.setForeground(new java.awt.Color(255, 255, 255));
        chkbx_passingType.setText("Passing");
        chkbx_passingType.setToolTipText("");

        chkbx_scoringType.setForeground(new java.awt.Color(255, 255, 255));
        chkbx_scoringType.setText("Scoring");

        chkbx_goalieType.setForeground(new java.awt.Color(255, 255, 255));
        chkbx_goalieType.setText("Goalie");

        txtfld_strengths.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lbl_robotStrengths.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lbl_robotStrengths.setForeground(new java.awt.Color(255, 255, 255));
        lbl_robotStrengths.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_robotStrengths.setText("Robot Strengths");

        txtfld_weaknesses.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lbl_robotWeaknesses.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lbl_robotWeaknesses.setForeground(new java.awt.Color(255, 255, 255));
        lbl_robotWeaknesses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_robotWeaknesses.setText("Robot Weaknesses");

        txtpn_notes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(txtpn_notes);

        lbl_notes.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lbl_notes.setForeground(new java.awt.Color(255, 255, 255));
        lbl_notes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_notes.setText("General Notes");

        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back(evt);
            }
        });

        btn_save.setText("Save Team");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(btn_back)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(lbl_title, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 278, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, btn_delete, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(lbl_teamNumber, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(lbl_teamName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(lbl_robotType, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .add(txtfld_teamName)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(9, 9, 9)
                        .add(chkbx_scoringType)
                        .add(66, 66, 66)
                        .add(chkbx_passingType)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(chkbx_goalieType))
                    .add(lbl_robotStrengths, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(lbl_robotWeaknesses, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(txtfld_weaknesses)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, txtfld_strengths)
                    .add(lbl_notes, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .add(btn_save, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lbl_title)
                    .add(btn_back))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lbl_teamNumber)
                .add(6, 6, 6)
                .add(lbl_teamName)
                .add(0, 0, 0)
                .add(txtfld_teamName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(lbl_robotType)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(chkbx_scoringType)
                        .add(chkbx_goalieType))
                    .add(chkbx_passingType))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lbl_robotStrengths)
                .add(0, 0, 0)
                .add(txtfld_strengths, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(lbl_robotWeaknesses)
                .add(0, 0, 0)
                .add(txtfld_weaknesses, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(lbl_notes)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(btn_save, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(btn_delete))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*takes the event as a parameter. Asks the user to confirm the deletion of the team. returns nothing*/
    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        //ask the user to confirm the deletion of the team and get the number of the clicked button
        int int_delete = JOptionPane.showConfirmDialog(null, "Do you really want to delete all data for " 
                + frct_team.int_teamNumber + "?", "Delete Team", JOptionPane.YES_NO_OPTION);

        //if the delete button was selected
        if (int_delete == JOptionPane.YES_OPTION)
        {
            //delete the game
            this.confirmedDelete();
        }
        
    }//GEN-LAST:event_btn_deleteActionPerformed

    //takes no paramters, deletes the team from the db and pops the frame
    public void confirmedDelete()
    {   
        //remove the team from the database
        frct_team.removeFromDB();
        
        //pop the frame from the view
        super.popFrame();
    }
    
    /*takes the event as a parameter. Saves the team to the db and pops the frame. returns nothing*/
    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        //cacluate the value for the robot type
        int int_robotType = (chkbx_scoringType.isSelected() ? Constants.int_SCORING : 0) 
                                + (chkbx_passingType.isSelected() ? Constants.int_PASSING : 0) 
                                + (chkbx_goalieType.isSelected() ? Constants.int_GOALIE : 0);
        
        //put the team name in a seperate string
        String str_teamName = txtfld_teamName.getText();
        //put the strengths in a seperate string
        String str_strengths = txtfld_strengths.getText();
        //put the weaknesses in a seperate string
        String str_weaknesses = txtfld_weaknesses.getText();
        //put the notes in a seperate string
        String str_notes = txtpn_notes.getText();
        
        //save the team data to a team object
        frct_team = new FRCTeam(frct_team.int_teamNumber, str_teamName, int_robotType,
                str_strengths, str_weaknesses, str_notes);
        
        //add/replace the team in the database
        frct_team.addToDB();
        
        //pop the frame from the view
        super.popFrame();
    }//GEN-LAST:event_btn_saveActionPerformed

    /*takes the event as a parameter. Pops the frame. returns nothing*/
    private void back(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back
        //call the super class' back function 
        super.popFrame();
    }//GEN-LAST:event_back

    /*takes no parameters, checks if the team number is 0 (meaning it doesnt exist in the db) 
    and pops the frame if the team is non existant. Reutnrs nothing */
    public void becameVisible()
    {
        if (frct_team.int_teamNumber == 0)
        {
            //let the user know no entry exists
            JOptionPane.showConfirmDialog(null, "No Entry Exists for that team.", "Return to Menu", JOptionPane.DEFAULT_OPTION);
            
            //go back to the previous frame
            this.back(null);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_save;
    private javax.swing.JCheckBox chkbx_goalieType;
    private javax.swing.JCheckBox chkbx_passingType;
    private javax.swing.JCheckBox chkbx_scoringType;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_notes;
    private javax.swing.JLabel lbl_robotStrengths;
    private javax.swing.JLabel lbl_robotType;
    private javax.swing.JLabel lbl_robotWeaknesses;
    private javax.swing.JLabel lbl_teamName;
    private javax.swing.JLabel lbl_teamNumber;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JTextField txtfld_strengths;
    private javax.swing.JTextField txtfld_teamName;
    private javax.swing.JTextField txtfld_weaknesses;
    private javax.swing.JTextPane txtpn_notes;
    // End of variables declaration//GEN-END:variables

}
